name: API-Sale-Phone CI/CD

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with: # We set all our secrets here for the action, these won't be shown in the action logs
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                script: |
                    cd /var/www/api-sale-phone # we move into our app's folder
                    git pull # we pull any changes from git
                    yarn install # we install any missing dependencies and remove all dependencies not necessary
                    yarn run build # we build our app
                    pm2 reload api-sale-phone:4001 # we reload the app via PM2